# Generated by Django 5.0.1 on 2024-02-23 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Film', '0003_film_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='likes',
        ),
    ]
